services:
  b-market:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8006:8006"
    container_name: b-market-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      # 可选：持久化数据库
      - ./data:/app/api/data
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8006/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 